language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t naresh4005/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naresh4005/docker-react npm run test

